alias la="la -A"
alias ll="ls -l"
alias st="svn status  | grep \"[MACDX?]\" | sort"
alias vim="open -a /Applications/MacVim.app"
alias yui="java -jar ~/util/tools/yui-compressor.jar"
alias gth="open `git remote -v | grep origin | head -n1 | awk '{print $2}' | sed 's/:/\//' | sed 's/git@/http:\/\//g' | sed 's/\.git//g'`"
